name: Content Generation

on:
  workflow_dispatch:
  schedule:
    - cron: '0 6 * * 1,3,5'

jobs:
  run-script:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v2
      - name: Run script
        run: npx zx --install ./.bin/content.mjs
        env:
          NOTION_API_TOKEN: ${{ secrets.NOTION_API_TOKEN }}
          OPENAI_API_TOKEN: ${{ secrets.OPENAI_API_TOKEN }}
